CREATE TABLE quote_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quote_id BIGINT UNSIGNED NOT NULL, position INT UNSIGNED NOT NULL, description VARCHAR(500) NOT NULL, quantity DECIMAL(15,2) NOT NULL DEFAULT 1.00, unit VARCHAR(50) NULL, unit_price DECIMAL(15,2) NOT NULL, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00, line_total DECIMAL(15,2) GENERATED ALWAYS AS (ROUND(quantity * unit_price * (1 + tax_rate / 100), 2)) STORED,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_quote_items_position (quote_id,position),
 CONSTRAINT chk_qi_values CHECK (quantity > 0 AND unit_price >= 0 AND tax_rate BETWEEN 0 AND 100), CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
